[theme]
primaryColor             = "#2563EB"
backgroundColor          = "#EFF6FF"
secondaryBackgroundColor = "#DBEAFE"
textColor                = "#1E293B"
font                     = "sans serif"

[server]
maxUploadSize = 200
