[theme]
primaryColor             = "#0891B2"
backgroundColor          = "#ECFEFF"
secondaryBackgroundColor = "#CFFAFE"
textColor                = "#1E293B"
font                     = "sans serif"

[server]
maxUploadSize = 200
